# Application configuration for Development

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/exam_service_db
      auto-index-creation: true

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: password
    virtual-host: /
    connection-timeout: 30000
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 2
        acknowledge-mode: auto
        prefetch: 5
        concurrency: 1
        max-concurrency: 3

logging:
  level:
    com.eximia.exams: DEBUG
    org.springframework.amqp: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.web: DEBUG

springdoc:
  swagger-ui:
    enabled: true
    operations-sorter: method