# Base application configuration

server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: exams-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  prometheus:
    metrics:
      export:
        enabled: true

app:
  rabbitmq:
    exchanges:
      exam: exam.exchange
    queues:
      exam-created: exam.created.queue
      exam-updated: exam.updated.queue
      exam-deleted: exam.deleted.queue
    routing-keys:
      exam-created: exam.created
      exam-updated: exam.updated
      exam-deleted: exam.deleted

  mongodb:
    collections:
      exams: exams

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  info:
    title: Exams Service API
    description: Microservice for CRUD operations about exams
    version: 1.0.0